# Lower version for compatibility, update if need to
version: "2.3"
services:
  detectron2:
    container_name: dex_detectron2_docker
    network_mode: host
    build:
      context: https://github.com/pduy110/docker_detectron2.git#main
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
    shm_size: "20gb"
    ulimits:
      memlock: -1
      stack: 67108864
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro

      # Using a persistent cache directory to prevent models from being re-downloaded on every run,
      - '$HOME/.torch/fvcore_cache:/tmp:rw'

      # Add Mahla's shared drive
      - '/home/anyone/Desktop/Mahla/detectron2:/detectron2'

      # X11 Forwarding for someone
      - '$HOME/.Xauthority:/root/.Xauthority:rw'

    # Add the required ports as in the Gdocs instructions
    ports:
      - '5000:8888'
      - '5001:6006'

    environment:
      - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all

      # Not exactly sure what is this for??? 
      - QT_X11_NO_MITSHM=1
      
    # Uncomment with proper source to access webcam from docker
    # devices: 
    #   - /dev/video0:/dev/video0

    #****** IMPORTANT:
    # To prevent docker-compose up from exiting with code 0 as with have no running processes, need to add tty:true
    tty: true


